package views;

import DAO.Sanphamdao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sanpham;
import repository.SanPhamRepo;

/**
 *
 * @author Admin
 */
public class SanPhamView extends javax.swing.JPanel {

    private SanPhamRepo repo = new SanPhamRepo();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;

    /**
     * Creates new form SanPhamView
     */
    public SanPhamView() {
        initComponents();
        this.filltotable(repo.getall());
        loadcombobox();
    }

    void filltotable(ArrayList<Sanpham> list) {
        mol = (DefaultTableModel) tblSanpham.getModel();
        mol.setRowCount(0);
        for (Sanpham sanpham : list) {
            mol.addRow(sanpham.addtorow());
        }
    }

    void showdata(int i) {
        txtmasp.setText(tblSanpham.getValueAt(i, 1).toString());
        txttensp.setText(tblSanpham.getValueAt(i, 2).toString());
        txtmota.setText(tblSanpham.getValueAt(i, 3).toString());

        String tenLSP = tblSanpham.getValueAt(i, 4).toString().trim().toLowerCase();

        for (int j = 0; j < cbbLoaisp.getItemCount(); j++) {
            if (cbbLoaisp.getItemAt(j).trim().toLowerCase().equals(tenLSP)) {
                cbbLoaisp.setSelectedIndex(j);
                break;
            }
        }
    }

    void loadcombobox() {
        Sanphamdao dao = new Sanphamdao();
        cbbLoaisp.removeAllItems();
        for (String item : dao.getLoaiSanPhamList()) {
            cbbLoaisp.addItem(item); // Chỉ hiển thị tên nhưng có thể tìm theo ID
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanpham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        txtmota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbLoaisp = new javax.swing.JComboBox<>();
        btnADD = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnXOA = new javax.swing.JButton();

        tblSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "mã sản phẩm", "Tên sản phẩm", "Mô tả", "Tên LSP", "Trạng thái"
            }
        ));
        tblSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanpham);

        jLabel1.setText("mã sản phẩm");

        jLabel2.setText("Tên sản phẩm");

        jLabel4.setText("Mô tả");

        jLabel5.setText("loai sản phẩm");

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnXOA.setText("ẨN");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbbLoaisp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnADD)
                                .addGap(30, 30, 30)
                                .addComponent(btnUPDATE)
                                .addGap(35, 35, 35)
                                .addComponent(btnXOA)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD)
                    .addComponent(btnUPDATE)
                    .addComponent(btnXOA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sanpham", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int i = tblSanpham.getSelectedRow(); // Lấy dòng đang chọn
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ma = txtmasp.getText(); // Lấy mã màu từ ô nhập liệu

        int confirm = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa sản phẩm này?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (repo.remove(ma) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filltotable(repo.getall()); // Cập nhật bảng sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        i = tblSanpham.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần update");
        } else {
            String ma = txtmasp.getText();
            Sanpham sp = this.readform();
            if (sp != null) {
                if (repo.update(sp, ma) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    this.filltotable(repo.getall());
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
        }
    }

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Sanpham sp = this.readform();
        if (sp == null) {
            return; // Validation failed, don't proceed
        }
        if (repo.add(sp) > 0) {
            JOptionPane.showMessageDialog(this, "lưu thành công");
            this.filltotable(repo.getall());
        } else {
            JOptionPane.showMessageDialog(this, "lưu thất bại");
        }
    }

    private void tblSanphamMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        i = tblSanpham.getSelectedRow();
        this.showdata(i);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JButton btnXOA;
    private javax.swing.JComboBox<String> cbbLoaisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblSanpham;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtmota;
    private javax.swing.JTextField txttensp;
    // End of variables declaration

    Sanpham readform() {
        String masp, tensp, mota;
        int idlsp;
        masp = txtmasp.getText();
        tensp = txttensp.getText();
        mota = txtmota.getText();

        // Validation
        if (masp.isEmpty() || tensp.isEmpty() || mota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return null;
        }

        try {
            idlsp = Integer.parseInt(cbbLoaisp.getSelectedItem().toString()); // Chuyển String → int
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Loại sản phẩm không hợp lệ!");
            return null;
        }

        return new Sanpham(i, masp, tensp, mota, idlsp, Boolean.TRUE);
    }
}